package com.feng.spring.entity;

public class Contact {
    private String uuid;

    private String chatroomid;

    private String sex;

    private String attrstatus;

    private String statues;

    private String pyquanpin;

    private String encrychatroomid;

    private String displayname;

    private String verifyflag;

    private String unifriend;

    private String contactflag;

    private String username;

    private String memberlist;

    private String starfriend;

    private String headimgurl;

    private String appaccountflag;


    private String membercount;

    private String remarkpyinitial;

    private String city;

    private String nickname;


    private String province;

    private String snsflag;

    private String alias;

    private String keyword;

    private String hideinputbarflag;

    private String signature;

    private String remarkname;

    private String remarkpyquanpin;

    private String uin;

    private String owneruin;

    private String isowner;

    private String pyinitial;

    private String owername;

    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.uuid
     *
     * @param uuid the value for contact.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.ChatRoomId
     *
     * @return the value of contact.ChatRoomId
     *
     * @mbggenerated
     */
    public String getChatroomid() {
        return chatroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.ChatRoomId
     *
     * @param chatroomid the value for contact.ChatRoomId
     *
     * @mbggenerated
     */
    public void setChatroomid(String chatroomid) {
        this.chatroomid = chatroomid == null ? null : chatroomid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.Sex
     *
     * @return the value of contact.Sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.Sex
     *
     * @param sex the value for contact.Sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.AttrStatus
     *
     * @return the value of contact.AttrStatus
     *
     * @mbggenerated
     */
    public String getAttrstatus() {
        return attrstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.AttrStatus
     *
     * @param attrstatus the value for contact.AttrStatus
     *
     * @mbggenerated
     */
    public void setAttrstatus(String attrstatus) {
        this.attrstatus = attrstatus == null ? null : attrstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.Statues
     *
     * @return the value of contact.Statues
     *
     * @mbggenerated
     */
    public String getStatues() {
        return statues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.Statues
     *
     * @param statues the value for contact.Statues
     *
     * @mbggenerated
     */
    public void setStatues(String statues) {
        this.statues = statues == null ? null : statues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.PYQuanPin
     *
     * @return the value of contact.PYQuanPin
     *
     * @mbggenerated
     */
    public String getPyquanpin() {
        return pyquanpin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.PYQuanPin
     *
     * @param pyquanpin the value for contact.PYQuanPin
     *
     * @mbggenerated
     */
    public void setPyquanpin(String pyquanpin) {
        this.pyquanpin = pyquanpin == null ? null : pyquanpin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.EncryChatRoomId
     *
     * @return the value of contact.EncryChatRoomId
     *
     * @mbggenerated
     */
    public String getEncrychatroomid() {
        return encrychatroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.EncryChatRoomId
     *
     * @param encrychatroomid the value for contact.EncryChatRoomId
     *
     * @mbggenerated
     */
    public void setEncrychatroomid(String encrychatroomid) {
        this.encrychatroomid = encrychatroomid == null ? null : encrychatroomid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.DisplayName
     *
     * @return the value of contact.DisplayName
     *
     * @mbggenerated
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.DisplayName
     *
     * @param displayname the value for contact.DisplayName
     *
     * @mbggenerated
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.VerifyFlag
     *
     * @return the value of contact.VerifyFlag
     *
     * @mbggenerated
     */
    public String getVerifyflag() {
        return verifyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.VerifyFlag
     *
     * @param verifyflag the value for contact.VerifyFlag
     *
     * @mbggenerated
     */
    public void setVerifyflag(String verifyflag) {
        this.verifyflag = verifyflag == null ? null : verifyflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.UniFriend
     *
     * @return the value of contact.UniFriend
     *
     * @mbggenerated
     */
    public String getUnifriend() {
        return unifriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.UniFriend
     *
     * @param unifriend the value for contact.UniFriend
     *
     * @mbggenerated
     */
    public void setUnifriend(String unifriend) {
        this.unifriend = unifriend == null ? null : unifriend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.ContactFlag
     *
     * @return the value of contact.ContactFlag
     *
     * @mbggenerated
     */
    public String getContactflag() {
        return contactflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.ContactFlag
     *
     * @param contactflag the value for contact.ContactFlag
     *
     * @mbggenerated
     */
    public void setContactflag(String contactflag) {
        this.contactflag = contactflag == null ? null : contactflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.UserName
     *
     * @return the value of contact.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.UserName
     *
     * @param username the value for contact.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.MemberList
     *
     * @return the value of contact.MemberList
     *
     * @mbggenerated
     */
    public String getMemberlist() {
        return memberlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.MemberList
     *
     * @param memberlist the value for contact.MemberList
     *
     * @mbggenerated
     */
    public void setMemberlist(String memberlist) {
        this.memberlist = memberlist == null ? null : memberlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.StarFriend
     *
     * @return the value of contact.StarFriend
     *
     * @mbggenerated
     */
    public String getStarfriend() {
        return starfriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.StarFriend
     *
     * @param starfriend the value for contact.StarFriend
     *
     * @mbggenerated
     */
    public void setStarfriend(String starfriend) {
        this.starfriend = starfriend == null ? null : starfriend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.HeadImgUrl
     *
     * @return the value of contact.HeadImgUrl
     *
     * @mbggenerated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.HeadImgUrl
     *
     * @param headimgurl the value for contact.HeadImgUrl
     *
     * @mbggenerated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.AppAccountFlag
     *
     * @return the value of contact.AppAccountFlag
     *
     * @mbggenerated
     */
    public String getAppaccountflag() {
        return appaccountflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.AppAccountFlag
     *
     * @param appaccountflag the value for contact.AppAccountFlag
     *
     * @mbggenerated
     */
    public void setAppaccountflag(String appaccountflag) {
        this.appaccountflag = appaccountflag == null ? null : appaccountflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.MemberCount
     *
     * @return the value of contact.MemberCount
     *
     * @mbggenerated
     */
    public String getMembercount() {
        return membercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.MemberCount
     *
     * @param membercount the value for contact.MemberCount
     *
     * @mbggenerated
     */
    public void setMembercount(String membercount) {
        this.membercount = membercount == null ? null : membercount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.RemarkPYInitial
     *
     * @return the value of contact.RemarkPYInitial
     *
     * @mbggenerated
     */
    public String getRemarkpyinitial() {
        return remarkpyinitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.RemarkPYInitial
     *
     * @param remarkpyinitial the value for contact.RemarkPYInitial
     *
     * @mbggenerated
     */
    public void setRemarkpyinitial(String remarkpyinitial) {
        this.remarkpyinitial = remarkpyinitial == null ? null : remarkpyinitial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.City
     *
     * @return the value of contact.City
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.City
     *
     * @param city the value for contact.City
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.NickName
     *
     * @return the value of contact.NickName
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.NickName
     *
     * @param nickname the value for contact.NickName
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.Province
     *
     * @return the value of contact.Province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.Province
     *
     * @param province the value for contact.Province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.SnsFlag
     *
     * @return the value of contact.SnsFlag
     *
     * @mbggenerated
     */
    public String getSnsflag() {
        return snsflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.SnsFlag
     *
     * @param snsflag the value for contact.SnsFlag
     *
     * @mbggenerated
     */
    public void setSnsflag(String snsflag) {
        this.snsflag = snsflag == null ? null : snsflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.Alias
     *
     * @return the value of contact.Alias
     *
     * @mbggenerated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.Alias
     *
     * @param alias the value for contact.Alias
     *
     * @mbggenerated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.KeyWord
     *
     * @return the value of contact.KeyWord
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.KeyWord
     *
     * @param keyword the value for contact.KeyWord
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.HideInputBarFlag
     *
     * @return the value of contact.HideInputBarFlag
     *
     * @mbggenerated
     */
    public String getHideinputbarflag() {
        return hideinputbarflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.HideInputBarFlag
     *
     * @param hideinputbarflag the value for contact.HideInputBarFlag
     *
     * @mbggenerated
     */
    public void setHideinputbarflag(String hideinputbarflag) {
        this.hideinputbarflag = hideinputbarflag == null ? null : hideinputbarflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.Signature
     *
     * @return the value of contact.Signature
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.Signature
     *
     * @param signature the value for contact.Signature
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.RemarkName
     *
     * @return the value of contact.RemarkName
     *
     * @mbggenerated
     */
    public String getRemarkname() {
        return remarkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.RemarkName
     *
     * @param remarkname the value for contact.RemarkName
     *
     * @mbggenerated
     */
    public void setRemarkname(String remarkname) {
        this.remarkname = remarkname == null ? null : remarkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.RemarkPYQuanPin
     *
     * @return the value of contact.RemarkPYQuanPin
     *
     * @mbggenerated
     */
    public String getRemarkpyquanpin() {
        return remarkpyquanpin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.RemarkPYQuanPin
     *
     * @param remarkpyquanpin the value for contact.RemarkPYQuanPin
     *
     * @mbggenerated
     */
    public void setRemarkpyquanpin(String remarkpyquanpin) {
        this.remarkpyquanpin = remarkpyquanpin == null ? null : remarkpyquanpin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.Uin
     *
     * @return the value of contact.Uin
     *
     * @mbggenerated
     */
    public String getUin() {
        return uin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.Uin
     *
     * @param uin the value for contact.Uin
     *
     * @mbggenerated
     */
    public void setUin(String uin) {
        this.uin = uin == null ? null : uin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.OwnerUin
     *
     * @return the value of contact.OwnerUin
     *
     * @mbggenerated
     */
    public String getOwneruin() {
        return owneruin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.OwnerUin
     *
     * @param owneruin the value for contact.OwnerUin
     *
     * @mbggenerated
     */
    public void setOwneruin(String owneruin) {
        this.owneruin = owneruin == null ? null : owneruin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.IsOwner
     *
     * @return the value of contact.IsOwner
     *
     * @mbggenerated
     */
    public String getIsowner() {
        return isowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.IsOwner
     *
     * @param isowner the value for contact.IsOwner
     *
     * @mbggenerated
     */
    public void setIsowner(String isowner) {
        this.isowner = isowner == null ? null : isowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.PYInitial
     *
     * @return the value of contact.PYInitial
     *
     * @mbggenerated
     */
    public String getPyinitial() {
        return pyinitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.PYInitial
     *
     * @param pyinitial the value for contact.PYInitial
     *
     * @mbggenerated
     */
    public void setPyinitial(String pyinitial) {
        this.pyinitial = pyinitial == null ? null : pyinitial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.OwerName
     *
     * @return the value of contact.OwerName
     *
     * @mbggenerated
     */
    public String getOwername() {
        return owername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.OwerName
     *
     * @param owername the value for contact.OwerName
     *
     * @mbggenerated
     */
    public void setOwername(String owername) {
        this.owername = owername == null ? null : owername.trim();
    }
}
